#+title: Emacs Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes
#+STARTUP: overview

* STUFF TO LOAD FIRST
** straight setup

#+begin_src emacs-lisp 
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(eval-when-compile (require 'use-package))

#+end_src

** Automatic Package Updates

#+begin_src emacs-lisp
(use-package auto-package-update
  :straight t
  :custom
  (auto-package-update-interval 7)
  (auto-package-update-prompt-before-update t)
  (auto-package-update-hide-results t)
  :config
  (auto-package-update-maybe)
  (auto-package-update-at-time "09:00"))
#+end_src

** buffer-move

#+begin_src emacs-lisp
;; This file is for lazy people wanting to swap buffers without
;; typing C-x b on each window.

;;; Code:
(require 'windmove)

;;;###autoload
(defun buf-move-up ()
  "Swap the current buffer and the buffer above the split.
If there is no split, ie now window above the current one, an
error is signaled."
;;  "Switches between the current buffer, and the buffer above the
;;  split, if possible."
  (interactive)
  (let* ((other-win (windmove-find-other-window 'up))
	 (buf-this-buf (window-buffer (selected-window))))
    (if (null other-win)
        (error "No window above this one")
      ;; swap top with this one
      (set-window-buffer (selected-window) (window-buffer other-win))
      ;; move this one to top
      (set-window-buffer other-win buf-this-buf)
      (select-window other-win))))

;;;###autoload
(defun buf-move-down ()
"Swap the current buffer and the buffer under the split.
If there is no split, ie now window under the current one, an
error is signaled."
  (interactive)
  (let* ((other-win (windmove-find-other-window 'down))
	 (buf-this-buf (window-buffer (selected-window))))
    (if (or (null other-win)
            (string-match "^ \\*Minibuf" (buffer-name (window-buffer other-win))))
        (error "No window under this one")
      ;; swap top with this one
      (set-window-buffer (selected-window) (window-buffer other-win))
      ;; move this one to top
      (set-window-buffer other-win buf-this-buf)
      (select-window other-win))))

;;;###autoload
(defun buf-move-left ()
"Swap the current buffer and the buffer on the left of the split.
If there is no split, ie now window on the left of the current
one, an error is signaled."
  (interactive)
  (let* ((other-win (windmove-find-other-window 'left))
	 (buf-this-buf (window-buffer (selected-window))))
    (if (null other-win)
        (error "No left split")
      ;; swap top with this one
      (set-window-buffer (selected-window) (window-buffer other-win))
      ;; move this one to top
      (set-window-buffer other-win buf-this-buf)
      (select-window other-win))))

;;;###autoload
(defun buf-move-right ()
"Swap the current buffer and the buffer on the right of the split.
If there is no split, ie now window on the right of the current
one, an error is signaled."
  (interactive)
  (let* ((other-win (windmove-find-other-window 'right))
	 (buf-this-buf (window-buffer (selected-window))))
    (if (null other-win)
        (error "No right split")
      ;; swap top with this one
      (set-window-buffer (selected-window) (window-buffer other-win))
      ;; move this one to top
      (set-window-buffer other-win buf-this-buf)
      (select-window other-win))))
#+end_src

** Disable nativecomp warnings

#+begin_src emacs-lisp
(setq native-comp-async-report-warnings-errors nil)
#+end_src

* ALL THE ICONS

#+begin_src emacs-lisp
(use-package all-the-icons
  :straight t
  :if (display-graphic-p))

(use-package all-the-icons-dired
  :straight t
  :hook (dired-mode . (lambda () (all-the-icons-dired-mode t))))
#+end_src

* APP LAUNCHER

#+begin_src emacs-lisp
(use-package app-launcher
  :straight '(app-launcher :host github :repo "SebastienWae/app-launcher"))

;; emacsclient -cF "((visibility . nil))" -e "(emacs-run-launcher)"

(defmacro bookmark-selector-launcher (NAME WIDTH HEIGHT FUNCTION)
  "Define a launcher command.

Bookmark-selector is a package revolving around using emacs
outside of emacs to browse your bookmarks. Most of the commands
defined, consist of opening an emacs frame with only a
minibuffer, with a specified NAME, WIDTH and HEIGHT and inside it
calling FUNCTION and deleting the frame after the function
completes or is canceled."
  `(with-selected-frame (make-frame '((name . ,NAME)
                                      (minibuffer . only)
                                      (width . ,WIDTH)
                                      (height . ,HEIGHT)))
     (unwind-protect
         (funcall ,FUNCTION)
       (delete-frame))))

(defun emacs-run-launcher ()
  "Create and select a frame called emacs-run-launcher which consists only of a minibuffer and has specific dimensions. Runs app-launcher-run-app on that frame, which is an emacs command that prompts you to select an app and open it in a dmenu like behaviour. Delete the frame after that command has exited"
  (interactive)
  (bookmark-selector-launcher "emacs-run-launcher" 59 14 'app-launcher-run-app)
    (unwind-protect
        (funcall ,FUNCTION)
      (delete-frame)))
#+end_src

* BACKUP

#+begin_src emacs-lisp
(setq backup-directory-alist '((".*" . "~/.local/share/Trash/files")))
#+end_src

* COMPANY

Company]] is a text completion framework for Emacs. The name stands for "complete anything".  Completion will start automatically after you type a few letters. Use M-n and M-p to select, <return> to complete or <tab> to complete the common part.

#+begin_src emacs-lisp
(use-package company
  :straight t
  :defer 2
  :diminish
  :custom
  (company-begin-commands '(self-insert-command))
  (company-idle-delay .1)
  (company-minimum-prefix-length 2)
  (company-show-numbers t)
  (company-tooltip-align-annotations 't)
  (global-company-mode t))

(use-package company-box
  :straight t
  :after company
  :diminish
  :hook (company-mode . company-box-mode))
#+end_src

* COUNSEL
Counsel, a collection of Ivy-enhanced versions of common Emacs commands.

#+begin_src emacs-lisp
(use-package counsel
  :straight t
  :after ivy
  :diminish
  :config
    (counsel-mode)
    (setq ivy-initial-inputs-alist nil)) ;; removes starting ^ regex in M-x

#+end_src

* DASHBOARD
Emacs Dashboard is an extensible startup screen showing you recent files, bookmarks, agenda items and an Emacs banner.

#+begin_src emacs-lisp
(use-package dashboard
  :straight t
  :init
  (setq initial-buffer-choice 'dashboard-open)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "~/.config/emacs/art/ascii.txt")  ;; use custom image as banner
  (setq dashboard-center-content nil) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (agenda . 5 )
                          (bookmarks . 3)
                          (projects . 3)
                          (registers . 3)))
  :custom
  (dashboard-modify-heading-icons '((recents . "file-text")
				      (bookmarks . "book")))
  :config
  (dashboard-setup-startup-hook))

#+end_src

* DIMINISH
This package implements hiding or abbreviation of the modeline displays (lighters) of minor-modes.  With this package installed, you can add ':diminish' to any use-package block to hide that particular mode in the modeline.

#+begin_src emacs-lisp
(use-package diminish
  :straight t)

#+end_src

* DIRED

#+begin_src emacs-lisp
(use-package dired-open
  :straight t
  :config
  (setq dired-open-extensions '(("gif" . "sxiv")
                                ("jpg" . "sxiv")
                                ("png" . "sxiv")
                                ("mkv" . "mpv")
                                ("mp4" . "mpv"))))

(use-package peep-dired
  :straight t
  :after dired
  :hook (evil-normalize-keymaps . peep-dired-hook)
  :config
    (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
    (evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
    (evil-define-key 'normal peep-dired-mode-map (kbd "j") 'peep-dired-next-file)
    (evil-define-key 'normal peep-dired-mode-map (kbd "k") 'peep-dired-prev-file)
)

 (use-package dired-sidebar
  :straight t
  :bind (("C-x C-n" . dired-sidebar-toggle-sidebar))
  :commands (dired-sidebar-toggle-sidebar)
  :init
  (add-hook 'dired-sidebar-mode-hook
            (lambda ()
              (unless (file-remote-p default-directory)
                (auto-revert-mode))))
  :config
  (push 'toggle-window-split dired-sidebar-toggle-hidden-commands)
  (push 'rotate-windows dired-sidebar-toggle-hidden-commands)

  (setq dired-sidebar-subtree-line-prefix "__")
  (setq dired-sidebar-theme 'all-the-icons)
  (setq dired-sidebar-use-term-integration t)
  (setq dired-sidebar-use-custom-font t))

#+end_src

* TODO DIRVISH

* DRAG-STUFF
[[https://github.com/rejeep/drag-stuff.el][Drag Stuff]] is a minor mode for Emacs that makes it possible to drag stuff (words, region, lines) around in Emacs.  When 'drag-stuff-define-keys' is enabled, then the following keybindings are set: M-up, M-down, M-left, and M-right.

#+begin_src emacs-lisp
(use-package drag-stuff
  :straight t
  :init
  (drag-stuff-global-mode 1)
  (drag-stuff-define-keys))
#+end_src

* EDIFF
'ediff' is a diff program that is built into Emacs.  By default, 'ediff' splits files vertically and places the 'help' frame in its own window.  I have changed this so the two files are split horizontally and the 'help' frame appears as a lower split within the existing window.  Also, I create my own 'dt-ediff-hook' where I add 'j/k' for moving to next/prev diffs.  By default, this is set to 'n/p'.

#+begin_src emacs-lisp
(setq ediff-split-window-function 'split-window-horizontally
      ediff-window-setup-function 'ediff-setup-windows-plain)

(defun dt-ediff-hook ()
  (ediff-setup-keymap)
  (define-key ediff-mode-map "j" 'ediff-next-difference)
  (define-key ediff-mode-map "k" 'ediff-previous-difference))

(add-hook 'ediff-mode-hook 'dt-ediff-hook)
#+end_src

* EVIL
[[https://github.com/emacs-evil/evil][Evil]] is an extensible vi/vim layer for Emacs.  Because...let's face it.  The Vim keybindings are just plain better.

#+begin_src emacs-lisp
(defun efs/evil-hook ()
  (dolist (mode '(custom-mode
                  eshell-mode
                  git-rebase-mode
                  sauron-mode
                  term-mode))
    (add-to-list 'evil-emacs-state-modes mode)))

;; Expands to: (elpaca evil (use-package evil :demand t))
(use-package evil
    :straight t
    :init      ;; tweak evil's configuration before loading it
    (setq evil-want-integration t  ;; This is optional since it's already set to t by default.
          evil-want-keybinding nil
          evil-vsplit-window-right t
          evil-split-window-below t
          evil-undo-system 'undo-redo)  ;; Adds vim-like C-r redo functionality
    :config
    (add-hook 'evil-mode-hook 'efs/evil-hook)
    (evil-mode 1))

(use-package evil-collection
  :straight t
  :after evil
  :config
  ;; Do not uncomment this unless you want to specify each and every mode
  ;; that evil-collection should works with.  The following line is here
  ;; for documentation purposes in case you need it.
  ;; (setq evil-collection-mode-list '(calendar dashboard dired ediff info magit ibuffer))
  (add-to-list 'evil-collection-mode-list 'help) ;; evilify help mode
  (evil-collection-init))

(use-package evil-tutor
  :straight t)

;; Using RETURN to follow links in Org/Evil
;; Unmap keys in 'evil-maps if not done, (setq org-return-follows-link t) will not work
(with-eval-after-load 'evil-maps
  (define-key evil-motion-state-map (kbd "SPC") nil)
  (define-key evil-motion-state-map (kbd "RET") nil)
  (define-key evil-motion-state-map (kbd "TAB") nil))
;; Setting RETURN key in org-mode to follow links
  (setq org-return-follows-link  t)

#+end_src

* FLYCHECK
Install =luacheck= from your Linux distro's repositories for flycheck to work correctly with lua files.  Install =python-pylint= for flycheck to work with python files.  Haskell works with flycheck as long as =haskell-ghc= or =haskell-stack-ghc= is installed.  For more information on language support for flycheck, [[https://www.flycheck.org/en/latest/languages.html][read this]].

#+begin_src emacs-lisp
(use-package flycheck
  :straight t
  :defer t
  :diminish
  :init (global-flycheck-mode))

#+end_src

* FONTS
Defining the various fonts that Emacs will use.

** Setting the Font Face

#+begin_src emacs-lisp
  (defun efs/set-font-faces ()
    (message "Setting faces!")
    (set-face-attribute 'default nil :font "JetBrainsMono Nerd Font" :height 135)

    ;; Set the fixed pitch face
    (set-face-attribute 'fixed-pitch nil :font "JetBrainsMono Nerd Font" :height 135)

    ;; Set the variable pitch face
    (set-face-attribute 'variable-pitch nil :font "JetBrainsMono Nerd Font" :height 135 :weight 'regular))

  (if (daemonp)
      (add-hook 'after-make-frame-functions
                (lambda (frame)
                  (setq doom-modeline-icon t)
                  (with-selected-frame frame
                    (efs/set-font-faces))))
    (efs/set-font-faces))

#+end_src
** Zooming In/Out

You can use the bindings CTRL plus =/- for zooming in/out.  You can also use CTRL plus the mouse wheel for zooming in/out.

#+begin_src emacs-lisp
(global-set-key (kbd "C-=") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
#+end_src

* GENERAL KEYBINDINGS
CLOSED: [2024-01-05 Fri 20:29]
** General

#+begin_src emacs-lisp
(use-package general
  :straight t
  :config
  (general-evil-setup)

  ;; set up 'SPC' as the global leader key
  (general-create-definer efs/leader-keys
    :states '(normal insert visual emacs)
    :keymaps 'override
    :prefix "SPC" ;; set leader
    :global-prefix "M-SPC") ;; access leader in insert mode
#+end_src

** Basic Stuff

#+begin_src emacs-lisp
(efs/leader-keys
 "SPC" '(counsel-M-x :wk "counsel M-x")
 "f f" '(find-file :wk "find file")
  "=" '(perspective-map :wk "perspective") ;; lists all the perspective keybindings
 "/" '(comment-line :wk "comment lines")
 "u" '(universal-argument :wk "universal argument"))
#+end_src

** Bookmarks/Buffers

#+begin_src emacs-lisp
(efs/leader-keys
 "b" '(:ignore t :wk "Bookmarks/Buffers")
 "b b" '(switch-to-buffer :wk "Switch to buffer")
 "b c" '(clone-indirect-buffer :wk "Create indirect buffer copy in a split")
 "b C" '(clone-indirect-buffer-other-window :wk "Clone indirect buffer in new window")
 "b d" '(bookmark-delete :wk "Delete bookmark")
 "b i" '(ibuffer :wk "Ibuffer")
 "b k" '(kill-current-buffer :wk "Kill current buffer")
 "b K" '(kill-some-buffers :wk "Kill multiple buffers")
 "b l" '(list-bookmarks :wk "List bookmarks")
 "b m" '(bookmark-set :wk "Set bookmark")
 "b n" '(next-buffer :wk "Next buffer")
 "b p" '(previous-buffer :wk "Previous buffer")
 "b r" '(revert-buffer :wk "Reload buffer")
 "b R" '(rename-buffer :wk "Rename buffer")
 "b s" '(basic-save-buffer :wk "Save buffer")
 "b S" '(save-some-buffers :wk "Save multiple buffers")
 "b w" '(bookmark-save :wk "Save current bookmarks to bookmark file"))
#+end_src

** Dired

#+begin_src emacs-lisp
(efs/leader-keys
 "d" '(:ignore t :wk "Dired")
 "d d" '(dired :wk "Open dired")
 "d f" '(wdired-finish-edit :wk "Writable dired finish edit")
 "d j" '(dired-jump :wk "Dired jump to current")
 "d n" '(neotree-dir :wk "Open directory in neotree")
 "d p" '(peep-dired :wk "Peep-dired")
 "d w" '(wdired-change-to-wdired-mode :wk "Writable dired"))
#+end_src

** Ediff/Eshell/Eval

#+begin_src emacs-lisp
(efs/leader-keys
 "e" '(:ignore t :wk "Ediff/Eshell/Eval/EWW")
 "e b" '(eval-buffer :wk "Evaluate elisp in buffer")
 "e d" '(eval-defun :wk "Evaluate defun containing or after point")
 "e e" '(eval-expression :wk "Evaluate and elisp expression")
 "e f" '(ediff-files :wk "Run ediff on a pair of files")
 "e F" '(ediff-files3 :wk "Run ediff on three files")
 "e h" '(counsel-esh-history :which-key "Eshell history")
 "e l" '(eval-last-sexp :wk "Evaluate elisp expression before point")
 "e r" '(eval-region :wk "Evaluate elisp in region")
 "e R" '(eww-reload :which-key "Reload current page in EWW")
 "e s" '(eshell :which-key "Eshell"))
#+end_src

** Files

#+begin_src emacs-lisp
(efs/leader-keys
 "f" '(:ignore t :wk "Files")
 "f c" '((lambda () (interactive)
           (find-file "~/.config/emacs/config.org"))
         :wk "Open emacs config.org")
 "f p" '((lambda () (interactive)
           (dired "~/.config/emacs/"))
         :wk "Open user-emacs-directory in dired")
 "f d" '(find-grep-dired :wk "Search for string in files in DIR")
 "f g" '(counsel-grep-or-swiper :wk "Search for string current file")
 "f i" '((lambda () (interactive)
           (find-file "~/.config/emacs/init.el"))
         :wk "Open emacs init.el")
 "f j" '(counsel-file-jump :wk "Jump to a file below current directory")
 "f l" '(counsel-locate :wk "Locate a file")
 "f r" '(counsel-recentf :wk "Find recent files")
 "f u" '(sudo-edit-find-file :wk "Sudo find file")
 "f U" '(sudo-edit :wk "Sudo edit file"))
#+end_src

** Help

#+begin_src emacs-lisp
(efs/leader-keys
 "h" '(:ignore t :wk "Help")
 "h a" '(counsel-apropos :wk "Apropos")
 "h b" '(describe-bindings :wk "Describe bindings")
 "h c" '(describe-char :wk "Describe character under cursor")
 "h d" '(:ignore t :wk "Emacs documentation")
 "h d a" '(about-emacs :wk "About Emacs")
 "h d d" '(view-emacs-debugging :wk "View Emacs debugging")
 "h d f" '(view-emacs-FAQ :wk "View Emacs FAQ")
 "h d m" '(info-emacs-manual :wk "The Emacs manual")
 "h d n" '(view-emacs-news :wk "View Emacs news")
 "h d o" '(describe-distribution :wk "How to obtain Emacs")
 "h d p" '(view-emacs-problems :wk "View Emacs problems")
 "h d t" '(view-emacs-todo :wk "View Emacs todo")
 "h d w" '(describe-no-warranty :wk "Describe no warranty")
 "h e" '(view-echo-area-messages :wk "View echo area messages")
 "h f" '(describe-function :wk "Describe function")
 "h F" '(describe-face :wk "Describe face")
 "h g" '(describe-gnu-project :wk "Describe GNU Project")
 "h i" '(info :wk "Info")
 "h I" '(describe-input-method :wk "Describe input method")
 "h k" '(describe-key :wk "Describe key")
 "h l" '(view-lossage :wk "Display recent keystrokes and the commands run")
 "h L" '(describe-language-environment :wk "Describe language environment")
 "h m" '(describe-mode :wk "Describe mode")
 "h r" '(:ignore t :wk "Reload")
 "h r r" '((lambda () (interactive)
             (load-file "~/.config/emacs/init.el"))
           :wk "Reload emacs config")
 "h t" '(load-theme :wk "Load theme")
 "h v" '(describe-variable :wk "Describe variable")
 "h w" '(where-is :wk "Prints keybinding for command if set")
 "h x" '(describe-command :wk "Display full documentation for command"))
#+end_src

** Org

#+begin_src emacs-lisp
(efs/leader-keys
 "m" '(:ignore t :wk "Org")
 "m a" '(org-agenda :wk "Org agenda")
 "m e" '(org-export-dispatch :wk "Org export dispatch")
 "m i" '(org-toggle-item :wk "Org toggle item")
 "m t" '(org-todo :wk "Org todo")
 "m b" '(org-babel-tangle :wk "Org babel tangle")
 "m T" '(org-todo-list :wk "Org todo list"))

(efs/leader-keys
 "m d" '(:ignore t :wk "Date/deadline")
 "m d t" '(org-time-stamp :wk "Org time stamp"))
#+end_src

** Open

#+begin_src emacs-lisp
(efs/leader-keys
 "o" '(:ignore t :wk "Open")
 "o d" '(dashboard-open :wk "Dashboard")
 "o f" '(make-frame :wk "Open buffer in new frame")
 "o F" '(select-frame-by-name :wk "Select frame by name"))
#+end_src

** Projectile

#+begin_src emacs-lisp
;; projectile-command-map already has a ton of bindings
;; set for us, so no need to specify each individually.
(efs/leader-keys
 "p" '(projectile-command-map :wk "Projectile"))
#+end_src

** Search

#+begin_src emacs-lisp
(efs/leader-keys
 "s" '(:ignore t :wk "Search")
 "s d" '(dictionary-search :wk "Search dictionary")
 "s m" '(man :wk "Man pages")
 "s o" '(pdf-occur :wk "Pdf search lines matching STRING")
 "s t" '(tldr :wk "Lookup TLDR docs for a command")
 "s w" '(woman :wk "Similar to man but doesn't require man"))
#+end_src

** Toggle

#+begin_src emacs-lisp
(efs/leader-keys
 "t" '(:ignore t :wk "Toggle")
 "t e" '(eshell-toggle :wk "Toggle eshell")
 "t f" '(flycheck-mode :wk "Toggle flycheck")
 "t l" '(display-line-numbers-mode :wk "Toggle line numbers")
 "t n" '(neotree-toggle :wk "Toggle neotree file viewer")
 "t o" '(org-mode :wk "Toggle org mode")
 "t r" '(rainbow-mode :wk "Toggle rainbow mode")
 "t t" '(visual-line-mode :wk "Toggle truncated lines")
 "t v" '(vterm-toggle :wk "Toggle vterm"))
#+end_src

** Windows/Words

#+begin_src emacs-lisp
(efs/leader-keys
 "w" '(:ignore t :wk "Windows/Words")
 ;; Window splits
 "w c" '(evil-window-delete :wk "Close window")
 "w n" '(evil-window-new :wk "New window")
 "w s" '(evil-window-split :wk "Horizontal split window")
 "w v" '(evil-window-vsplit :wk "Vertical split window")
 ;; Window motions
 "w h" '(evil-window-left :wk "Window left")
 "w j" '(evil-window-down :wk "Window down")
 "w k" '(evil-window-up :wk "Window up")
 "w l" '(evil-window-right :wk "Window right")
 "w w" '(evil-window-next :wk "Goto next window")
 ;; Move Windows
 "w H" '(buf-move-left :wk "Buffer move left")
 "w J" '(buf-move-down :wk "Buffer move down")
 "w K" '(buf-move-up :wk "Buffer move up")
 "w L" '(buf-move-right :wk "Buffer move right")
 ;; Words
 "w d" '(downcase-word :wk "Downcase word")
 "w u" '(upcase-word :wk "Upcase word")
 "w =" '(count-words :wk "Count words/lines for buffer"))
)
#+end_src

* GIT PROGRAMS
** Git Time Machine
[[https://github.com/emacsmirror/git-timemachine][git-timemachine]] is a program that allows you to move backwards and forwards through a file's commits.  'SPC g t' will open the time machine on a file if it is in a git repo.  Then, while in normal mode, you can use 'CTRL-j' and 'CTRL-k' to move backwards and forwards through the commits.


#+begin_src emacs-lisp
(use-package git-timemachine
  :straight t
  :after git-timemachine
  :hook (evil-normalize-keymaps . git-timemachine-hook)
  :config
    (evil-define-key 'normal git-timemachine-mode-map (kbd "C-j") 'git-timemachine-show-previous-revision)
    (evil-define-key 'normal git-timemachine-mode-map (kbd "C-k") 'git-timemachine-show-next-revision)
)
#+end_src

** Magit
[[https://magit.vc/manual/][Magit]] is a full-featured git client for Emacs.

#+begin_src emacs-lisp
(use-package magit
  :straight t)
#+end_src

* HIGHLIGHT
Adding highlights to TODO and related words.

#+begin_src emacs-lisp
(use-package hl-todo
  :straight t
  :hook ((org-mode . hl-todo-mode)
         (prog-mode . hl-todo-mode))
  :config
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces
        `(("TODO"       warning bold)
          ("FIXME"      error bold)
          ("HACK"       font-lock-constant-face bold)
          ("REVIEW"     font-lock-keyword-face bold)
          ("NOTE"       success bold)
          ("DEPRECATED" font-lock-doc-face bold))))
#+end_src

* IVY
+ Ivy, a generic completion mechanism for Emacs.
+ Ivy-rich allows us to add descriptions alongside the commands in M-x.

#+begin_src emacs-lisp
(use-package ivy
  :straight t
  :bind
  ;; ivy-resume resumes the last Ivy-based completion.
  (("C-c C-r" . ivy-resume)
   ("C-x B" . ivy-switch-buffer-other-window))
  :diminish
  :custom
  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "(%d/%d) ")
  (setq enable-recursive-minibuffers t)
  :config
  (ivy-mode))

(use-package all-the-icons-ivy-rich
  :straight t
  :init (all-the-icons-ivy-rich-mode 1))

(use-package ivy-rich
  :after ivy
  :straight t
  :init (ivy-rich-mode 1) ;; this gets us descriptions in M-x.
  :custom
  (ivy-virtual-abbreviate 'full
   ivy-rich-switch-buffer-align-virtual-buffer t
   ivy-rich-path-style 'abbrev)
  :config
  (ivy-set-display-transformer 'ivy-switch-buffer
                               'ivy-rich-switch-buffer-transformer))

#+end_src

* LINE NUMBERS

#+begin_src emacs-lisp
(global-display-line-numbers-mode -1)

(setq-default display-line-numbers-grow-only t
              display-line-numbers-width 2)

;; Enable line numbers for some modes
(dolist (mode '(prog-mode-hook
                conf-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode t))))
#+end_src

* MINIBUFFER ESCAPE
By default, Emacs requires you to hit ESC three times to escape quit the minibuffer.

#+begin_src emacs-lisp
(global-set-key [escape] 'keyboard-escape-quit)
#+end_src

* MODELINE
The modeline is the bottom status bar that appears in Emacs windows.  While you can create your own custom modeline, why go to the trouble when Doom Emacs already has a nice modeline package available.  For more information on what is available to configure in the Doom modeline, check out: [[https://github.com/seagle0128/doom-modeline][Doom Modeline]]

#+begin_src emacs-lisp
(use-package doom-modeline
  :straight t
  :init (doom-modeline-mode 1)
  :config
  (setq doom-modeline-height 35      ;; sets modeline height
        doom-modeline-bar-width 5    ;; sets right bar width
        doom-modeline-persp-name t   ;; adds perspective name to modeline
        doom-modeline-persp-icon t)) ;; adds folder icon next to persp name

#+end_src

* TODO ORG MODE

** Diminish Org Indent Mode
Removes "Ind" from showing in the modeline.

#+begin_src emacs-lisp
(eval-after-load 'org-indent '(diminish 'org-indent-mode))

#+end_src
** org-Bullets
Org-bullets gives us attractive bullets rather than asterisks.

#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-indent-mode)
(use-package org-bullets
  :straight t)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src
** org Level Headers
#+begin_src emacs-lisp
  (custom-set-faces
   '(org-level-1 ((t (:inherit outline-1 :height 1.3))))
   '(org-level-2 ((t (:inherit outline-2 :height 1.27))))
   '(org-level-3 ((t (:inherit outline-3 :height 1.23))))
   '(org-level-4 ((t (:inherit outline-4 :height 1.2))))
   '(org-level-5 ((t (:inherit outline-5 :height 1.17))))
   '(org-level-6 ((t (:inherit outline-5 :height 1.13))))
   '(org-level-7 ((t (:inherit outline-5 :height 1.1)))))
#+end_src
** org-Tempo
Org-tempo is not a separate package but a module within org that can be enabled.  Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag.  Other expansions available include:

| Typing the below + TAB | Expands to ...                          |
|------------------------+-----------------------------------------|
| <a                     | '#+BEGIN_EXPORT ascii' … '#+END_EXPORT  |
| <c                     | '#+BEGIN_CENTER' … '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' … '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' … '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' … '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' … '#+END_EXPORT'  |
| <l                     | '#+BEGIN_EXPORT latex' … '#+END_EXPORT' |
| <q                     | '#+BEGIN_QUOTE' … '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' … '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' … '#+END_VERSE'         |

#+begin_src emacs-lisp
(with-eval-after-load 'org
  ;; This is needed as of Org 9.2
  (require 'org-tempo)

  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("py" . "src python")))
#+end_src


** jupyter

#+begin_src emacs-lisp
(use-package jupyter 
  :straight t)

(use-package ob-async
  :straight t)

(setq ob-async-no-async-languages-alist '("jupyter-python" "jupyter-julia"))

#+end_src

** org-babel

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (org-babel-do-load-languages
      'org-babel-load-languages
      '((emacs-lisp . t)
      (python . t)
      (jupyter .t)))

  (push '("conf-unix" . conf-unix) org-src-lang-modes))
#+end_src

* PDFs
[[https://github.com/vedang/pdf-tools][pdf-tools]] is a replacement of DocView for viewing PDF files inside Emacs.  It uses the =poppler= library, which also means that 'pdf-tools' can by used to modify PDFs.  I use to disable 'display-line-numbers-mode' in 'pdf-view-mode' because line numbers crash it.

#+begin_src emacs-lisp
(use-package pdf-tools
  :straight t
  :defer t
  :commands (pdf-loader-install)
  :mode "\\.pdf\\'"
  :bind (:map pdf-view-mode-map
              ("j" . pdf-view-next-line-or-next-page)
              ("k" . pdf-view-previous-line-or-previous-page)
              ("C-=" . pdf-view-enlarge)
              ("C--" . pdf-view-shrink))
  :init (pdf-loader-install)
  :config (add-to-list 'revert-without-query ".pdf"))

(add-hook 'pdf-view-mode-hook #'(lambda () (interactive) (display-line-numbers-mode -1)))
#+end_src

* PERSPECTIVE
[[https://github.com/nex3/perspective-el][Perspective]] provides multiple named workspaces (or "perspectives") in Emacs, similar to multiple desktops in window managers.  Each perspective has its own buffer list and its own window layout, along with some other isolated niceties, like the [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Xref.html][xref]] ring.

#+begin_src emacs-lisp
(use-package perspective
  :straight t
  :custom
  ;; NOTE! I have also set 'SCP =' to open the perspective menu.
  ;; I'm only setting the additional binding because setting it
  ;; helps suppress an annoying warning message.
  (persp-mode-prefix-key (kbd "C-c M-p"))
  :init
  (persp-mode)
  :config
  ;; Sets a file to write to when we save states
  (setq persp-state-default-file "~/.config/emacs/sessions"))

;; This will group buffers by persp-name in ibuffer.
(add-hook 'ibuffer-hook
          (lambda ()
            (persp-ibuffer-set-filter-groups)
            (unless (eq ibuffer-sorting-mode 'alphabetic)
              (ibuffer-do-sort-by-alphabetic))))

;; Automatically save perspective states to file when Emacs exits.
(add-hook 'kill-emacs-hook #'persp-state-save)

#+end_src

* PROJECTILE
[[https://github.com/bbatsov/projectile][Projectile]] is a project interaction library for Emacs.  It should be noted that many projectile commands do not work if you have set "fish" as the "shell-file-name" for Emacs.  I had initially set "fish" as the "shell-file-name" in the Vterm section of this config, but oddly enough I changed it to "bin/sh" and projectile now works as expected, and Vterm still uses "fish" because my default user "sh" on my Linux system is "fish".

#+begin_src emacs-lisp
(use-package projectile
  :straight t
  :config
  (projectile-mode 1))
#+end_src

* RAINBOW DELIMITERS
Adding rainbow coloring to parentheses.

#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :straight t
  :hook ((emacs-lisp-mode . rainbow-delimiters-mode)
         (clojure-mode . rainbow-delimiters-mode)))

#+end_src

* RAINBOW MODE
Display the actual color as a background for any hex color value (ex. #ffffff).  The code block below enables rainbow-mode in all programming modes (prog-mode) as well as org-mode, which is why rainbow works in this document.

#+begin_src emacs-lisp
(use-package rainbow-mode
  :straight t
  :diminish
  :hook org-mode prog-mode)
#+end_src

* SANE DEFAULTS
The following settings are simple modes that are enabled (or disabled) so that Emacs functions more like you would expect a proper editor/IDE to function.

#+begin_src emacs-lisp
(delete-selection-mode 1)    ;; You can select text and delete it by typing.
(electric-indent-mode -1)    ;; Turn off the weird indenting that Emacs does by default.
(electric-pair-mode 1)       ;; Turns on automatic parens pairing
;; The following prevents <> from auto-pairing when electric-pair-mode is on.
;; Otherwise, org-tempo is broken when you try to <s TAB...
(add-hook 'org-mode-hook (lambda ()
           (setq-local electric-pair-inhibit-predicate
                   `(lambda (c)
                  (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c))))))
(global-auto-revert-mode t)  ;; Automatically show changes if the file has changed
(global-visual-line-mode t)  ;; Enable truncated lines
(menu-bar-mode -1)           ;; Disable the menu bar
(scroll-bar-mode -1)         ;; Disable the scroll bar
(tool-bar-mode -1)           ;; Disable the tool bar
(setq org-edit-src-content-indentation 0) ;; Set src block automatic indent to 0 instead of 2.
(setq use-file-dialog nil)   ;; No file dialog
(setq use-dialog-box nil)    ;; No dialog box
(setq pop-up-windows nil)    ;; No popup windows
#+end_src

* SHELLS

Eshell is an Emacs 'shell' that is written in Elisp.

#+begin_src emacs-lisp
(use-package eshell-toggle
  :straight t
  :custom
  (eshell-toggle-size-fraction 3)
  (eshell-toggle-use-projectile-root t)
  (eshell-toggle-run-command nil)
  (eshell-toggle-init-function #'eshell-toggle-init-ansi-term))

  (use-package eshell-syntax-highlighting
    :straight t
    :after esh-mode
    :config
    (eshell-syntax-highlighting-global-mode +1))

  ;; eshell-syntax-highlighting -- adds fish/zsh-like syntax highlighting.
  ;; eshell-rc-script -- your profile for eshell; like a bashrc for eshell.
  ;; eshell-aliases-file -- sets an aliases file for the eshell.

  (setq eshell-rc-script (concat user-emacs-directory "eshell/profile")
        eshell-aliases-file (concat user-emacs-directory "eshell/aliases")
        eshell-history-size 5000
        eshell-buffer-maximum-lines 5000
        eshell-hist-ignoredups t
        eshell-scroll-to-bottom-on-input t
        eshell-destroy-buffer-when-process-dies t
        eshell-visual-commands'("bash" "fish" "htop" "ssh" "top" "zsh"))
#+end_src

* SUDO EDIT
[[https://github.com/nflath/sudo-edit][sudo-edit]] gives us the ability to open files with sudo privileges or switch over to editing with sudo privileges if we initially opened the file without such privileges.

#+begin_src emacs-lisp
(use-package sudo-edit
  :straight t)
#+end_src

* TABS

#+begin_src emacs-lisp
(use-package centaur-tabs
  :straight t
  :init
  (setq centaur-tabs-enable-key-bindings t)
  :config
  (setq centaur-tabs-style "bar"
        centaur-tabs-height 32
        centaur-tabs-set-icons t
        centaur-tabs-show-new-tab-button t
        centaur-tabs-set-modified-marker t
        centaur-tabs-show-navigation-buttons t
        centaur-tabs-set-bar 'under
        centaur-tabs-show-count nil
        ;; centaur-tabs-label-fixed-length 15
        ;; centaur-tabs-gray-out-icons 'buffer
        ;; centaur-tabs-plain-icons t
        x-underline-at-descent-line t
        centaur-tabs-left-edge-margin nil)
  (centaur-tabs-change-fonts (face-attribute 'default :font) 110)
  (centaur-tabs-headline-match)
  ;; (centaur-tabs-enable-buffer-alphabetical-reordering)
  ;; (setq centaur-tabs-adjust-buffer-order t)
  (centaur-tabs-mode t)
  (setq uniquify-separator "/")
  (setq uniquify-buffer-name-style 'forward)
  (defun centaur-tabs-buffer-groups ()
    "`centaur-tabs-buffer-groups' control buffers' group rules.

Group centaur-tabs with mode if buffer is derived from `eshell-mode' `emacs-lisp-mode' `dired-mode' `org-mode' `magit-mode'.
All buffer name start with * will group to \"Emacs\".
Other buffer group by `centaur-tabs-get-group-name' with project name."
    (list
     (cond
      ;; ((not (eq (file-remote-p (buffer-file-name)) nil))
      ;; "Remote")
      ((or (string-equal "*" (substring (buffer-name) 0 1))
           (memq major-mode '(magit-process-mode
                              magit-status-mode
                              magit-diff-mode
                              magit-log-mode
                              magit-file-mode
                              magit-blob-mode
                              magit-blame-mode
                              )))
       "Emacs")
      ((derived-mode-p 'prog-mode)
       "Editing")
      ((derived-mode-p 'dired-mode)
       "Dired")
      ((memq major-mode '(helpful-mode
                          help-mode))
       "Help")
      ((memq major-mode '(org-mode
                          org-agenda-clockreport-mode
                          org-src-mode
                          org-agenda-mode
                          org-beamer-mode
                          org-indent-mode
                          org-bullets-mode
                          org-cdlatex-mode
                          org-agenda-log-mode
                          diary-mode))
       "OrgMode")
      (t
       (centaur-tabs-get-group-name (current-buffer))))))
  :hook
  (dashboard-mode . centaur-tabs-local-mode)
  (term-mode . centaur-tabs-local-mode)
  (calendar-mode . centaur-tabs-local-mode)
  (org-agenda-mode . centaur-tabs-local-mode)
  :bind
  ("C-<prior>" . centaur-tabs-backward)
  ("C-<next>" . centaur-tabs-forward)
  ("C-S-<prior>" . centaur-tabs-move-current-tab-to-left)
  ("C-S-<next>" . centaur-tabs-move-current-tab-to-right)
  (:map evil-normal-state-map
        ("g t" . centaur-tabs-forward)
        ("g T" . centaur-tabs-backward)))
#+end_src

* TERMINALS
** Vterm
Vterm is a terminal emulator within Emacs.  The 'shell-file-name' setting sets the shell to be used in M-x shell, M-x term, M-x ansi-term and M-x vterm.  By default, the shell is set to 'fish' but could change it to 'bash' or 'zsh' if you prefer.

#+begin_src emacs-lisp
(use-package vterm
  :straight t
  :config
  (setq shell-file-name "/usr/bin/zsh"
        vterm-max-scrollback 5000))
#+end_src

** Vterm-Toggle
[[https://github.com/jixiuf/vterm-toggle][vterm-toggle]] toggles between the vterm buffer and whatever buffer you are editing.

#+begin_src emacs-lisp
(use-package vterm-toggle
  :straight t
  :after vterm
  :config
  ;; When running programs in Vterm and in 'normal' mode, make sure that ESC
  ;; kills the program as it would in most standard terminal programs.
  (evil-define-key 'normal vterm-mode-map (kbd "<escape>") 'vterm--self-insert)
  (setq vterm-toggle-fullscreen-p nil)
  (setq vterm-toggle-scope 'project)
  (add-to-list 'display-buffer-alist
               '((lambda (buffer-or-name _)
                     (let ((buffer (get-buffer buffer-or-name)))
                       (with-current-buffer buffer
                         (or (equal major-mode 'vterm-mode)
                             (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                  (display-buffer-reuse-window display-buffer-at-bottom)
                  ;;(display-buffer-reuse-window display-buffer-in-direction)
                  ;;display-buffer-in-direction/direction/dedicated is added in emacs27
                  ;;(direction . bottom)
                  ;;(dedicated . t) ;dedicated is supported in emacs27
                  (reusable-frames . visible)
                  (window-height . 0.4))))
#+end_src

* THEME
#+begin_src emacs-lisp
(use-package catppuccin-theme
  :straight t)
(load-theme 'catppuccin :no-confirm)
(catppuccin-set-color 'base "#1E1E2E") ;; change base to #000000 for the currently active flavor
(catppuccin-set-color 'crust "#11111B" 'mocha) ;; change crust to #222222 for frappe
(catppuccin-reload)
#+end_src

* TLDR

#+begin_src emacs-lisp
(use-package tldr
  :straight t)
#+end_src

* TRANSPARENCY
With Emacs version 29, true transparency has been added.  I have turned transparency off by setting the alpha to '100'.  If you want some slight transparency, try setting alpha to '90'.  Of course, if you set alpha to '0', the background of Emacs would completely transparent.

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha-background . 95)) ; For all new frames henceforth

#+end_src

* WHICH-KEY

#+begin_src emacs-lisp
(use-package which-key
  :straight t
  :init
  (which-key-mode 1)
  :diminish
  :config
  (setq which-key-side-window-location 'bottom
    which-key-sort-order #'which-key-key-order-alpha
    which-key-allow-imprecise-window-fit nil
    which-key-sort-uppercase-first nil
    which-key-add-column-padding 1
    which-key-max-display-columns nil
    which-key-min-display-lines 6
    which-key-side-window-slot -10
    which-key-side-window-max-height 0.25
    which-key-idle-delay 0.8
    which-key-max-description-length 25
    which-key-allow-imprecise-window-fit nil
    which-key-separator " → " ))
#+end_src
